#!/bin/bash
function inArray
{
  local e
  for e in "${@:2}"; do
    [[ "$e" == "$1" ]] && return 0;
  done
  return 1
}

DIR_BLACKLIST=("release")

mkdir staging

for DIR in *; do
  if [ -d "${DIR}" ] && ! inArray "$DIR" "$DIR_BLACKLIST"; then
    cd $DIR
    zip -9 -r "$DIR.love" .
    cd ..
    mv "$DIR/$DIR.love" ./staging
  fi
done

cd ./staging
zip -r bundle.zip .
cd ..
mv ./staging/bundle.zip ./release/
rm -rf ./staging
