#!/bin/bash

DIR_BLACKLIST="release media staging"

for DIR in *; do
  if [ -d "${DIR}" ] && ! [ -z "${DIR_BLACKLIST##*$DIR*}" ]; then
    love-release "release/" "$DIR"
  fi
done

cd ./release
echo "Creating bundle.zip"
zip -r bundle.zip .
