[package]
name = "top-down-3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bevy = "0.6"
bevy = { version = "0.6", features = ["dynamic"] }
heron = { version = "2.2.0", features = ["3d"] }
